name: build-test-verify

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node deps
        run: npm ci || npm install

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r export/requirements.txt

      - name: Run unit tests
        run: npx jest --passWithNoTests

      - name: Deterministic export
        run: python3 export/export.py --out dist/exports/spark.json --deterministic

      - name: Verify checksum existence
        run: test -f SBOM/checksums.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spark-artifacts
          path: |
            dist/exports/spark.json
            SBOM/checksums.csv
            SBOM/provenance.json
